// Generated by CoffeeScript 1.7.1
define([], function() {
  return describe('Path reader', function() {
    return it('should', function() {
      return expect(true).to.equal(true);
    });
  });
});
