// Generated by CoffeeScript 1.7.1
define(['zone', 'memory-reader', 'airspace', 'text!./data/french.txt'], function(Zone, Reader, Airspace, data) {
  var simpleZone;
  simpleZone = Zone.parse(new Reader(data));
  return {
    simpleZone: simpleZone,
    airSpaceWithSimpleZone: new Airspace([simpleZone])
  };
});
