// Generated by CoffeeScript 1.7.1
define(function() {
  var Airspace;
  return Airspace = (function() {
    function Airspace(zones) {
      this.zones = zones;
    }

    return Airspace;

  })();
});
