// Generated by CoffeeScript 1.7.1
define(function() {
  var Reader;
  return Reader = (function() {
    function Reader() {}

    Reader.prototype.readLine = function() {};

    Reader.prototype.readNext = function() {};

    return Reader;

  })();
});
