// Generated by CoffeeScript 1.7.1
define(['./zone-parser', './helpers'], function(ZoneParser) {
  'use strict';
  var Zone;
  return Zone = (function() {
    function Zone(_arg) {
      this.name = _arg.name, this["class"] = _arg["class"], this.description = _arg.description, this.floor = _arg.floor, this.ceiling = _arg.ceiling, this.shapes = _arg.shapes;
    }

    Zone.lazyval('polygon', function() {
      var coordinates, shape, shapeCoords, _i, _len, _ref;
      coordinates = [];
      _ref = this.shapes;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        shape = _ref[_i];
        shapeCoords = shape.discretize();
        coordinates = coordinates.concat(shapeCoords);
      }
      return coordinates;
    });

    Zone.parse = function(reader) {
      var parser, zone;
      parser = new ZoneParser(reader);
      zone = parser.parse();
      return new Zone(zone);
    };

    return Zone;

  })();
});
