// Generated by CoffeeScript 1.7.1
define(function() {
  var Polygon;
  return Polygon = (function() {
    function Polygon() {
      this.points = [];
    }

    Polygon.prototype.addPath = function(path) {
      return this.points = points.concat(path.discretize());
    };

    return Polygon;

  })();
});
