// Generated by CoffeeScript 1.7.1
define(function() {
  var Zone;
  return Zone = (function() {
    function Zone(_arg) {
      this.name = _arg.name, this["class"] = _arg["class"], this.description = _arg.description, this.floor = _arg.floor, this.ceiling = _arg.ceiling, this.polygon = _arg.polygon;
    }

    return Zone;

  })();
});
