// Generated by CoffeeScript 1.7.1
define(function() {
  'use strict';
  var Converter, convertPoint, convertZone;
  convertPoint = function(point) {
    return [point.lng.decimalDegrees, point.lat.decimalDegrees];
  };
  convertZone = function(zone) {
    return {
      type: 'Feature',
      geometry: {
        type: 'Polygon',
        coordinates: [zone.polygon.map(convertPoint)]
      },
      properties: {
        name: zone.name,
        classCode: zone["class"].code,
        className: zone["class"].name,
        description: zone.description,
        floorFeet: zone.floor.feet,
        floorDesc: zone.floor.desc,
        ceilingFeet: zone.ceiling.feet,
        ceilingDesc: zone.ceiling.desc
      }
    };
  };
  return Converter = (function() {
    function Converter() {}

    Converter.prototype.toGeoJson = function(airspace) {
      return {
        type: 'FeatureCollection',
        features: airspace.zones.map(convertZone)
      };
    };

    return Converter;

  })();
});
