// Generated by CoffeeScript 1.7.1
define(function() {
  'use strict';
  var Converter, convertPoint, convertZone;
  convertPoint = function(point) {
    return [point.lat.decimalDegrees, point.lng.decimalDegrees];
  };
  convertZone = function(zone) {
    return {
      type: 'Feature',
      geometry: {
        type: 'Polygon',
        coordinates: zone.polygon.map(convertPoint)
      },
      properties: {
        name: zone.name,
        "class": zone["class"],
        description: zone.description,
        floor: zone.floor,
        ceiling: zone.ceiling
      }
    };
  };
  return Converter = (function() {
    function Converter() {}

    Converter.prototype.toGeoJson = function(airspace) {
      return {
        type: 'FeatureCollection',
        features: airspace.zones.map(convertZone)
      };
    };

    return Converter;

  })();
});
